#!/usr/bin/env bash
# Displays numbers from 1 to 20

length=1

while [ $length -le 20 ]
do
  echo "$length"
  case $length in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( length++ ))
done
